name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: '克隆项目'
        run: |
          git clone https://github.com/Zero-S1/xmly_speed.git ~/xmlyspeed
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: |
          cd ~/xmlyspeed
          pip install -r ./requirements.txt 
        
      - name: 'run 喜马拉雅极速版' 
        run: |
          cd ~/xmlyspeed
          python3 xmly_speed.py 
        env:
            QCZJ_GetUserInfoURL: ${{ secrets.QCZJ_GetUserInfoURL }} 
            QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }} 
            QCZJ_coinBODY: ${{ secrets.QCZJ_coinBODY }} 
            QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }} 
            QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }} 
            addCoinBODY: ${{ secrets.addCoinBODY }} 
            addCoin2BODY: ${{ secrets.addCoin2BODY }} 
            reportAssHEADER: ${{ secrets.reportAssHEADER }} 
            reportAssBODY: ${{ secrets.reportAssBODY }} 
            cointowalletBODY: ${{ secrets.cointowalletBODY }} 
            QCZJ_GoldcoinBODY: ${{ secrets.QCZJ_GoldcoinBODY }} 
            QCZJ_videoBODY: ${{ secrets.QCZJ_videoBODY }} 
            QCZJ_WelfarevideoBODY: ${{ secrets.QCZJ_WelfarevideoBODY }} 
            QCZJ_WelfareBODY: ${{ secrets.QCZJ_WelfareBODY }} 
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
    
