name: 汽车之家极速版签到

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: start
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye12/QCZJSPEED.git ~/qczjspeed
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/qczjspeed
          npm install
      - name: '运行 【汽车之家极速版】'
        run: |
          cd ~/qczjspeed/Task
          node qczjspeed.js
        env:
          TZ: Asia/shanghai
          QCZJ_GetUserInfoURL: ${{ secrets.QCZJ_GetUserInfoURL }} 
          QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }} 
          QCZJ_coinBODY: ${{ secrets.QCZJ_coinBODY }} 
          QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }} 
          QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }} 
          QCZJ_addCoinBODY: ${{ secrets.addCoinBODY }} 
          QCZJ_addCoin2BODY: ${{ secrets.addCoin2BODY }} 
          QCZJ_reportAssHEADER: ${{ secrets.reportAssHEADER }} 
          QCZJ_reportAssBODY: ${{ secrets.reportAssBODY }} 
          QCZJ_cointowalletBODY: ${{ secrets.cointowalletBODY }} 
          QCZJ_GoldcoinBODY: ${{ secrets.QCZJ_GoldcoinBODY }} 
          QCZJ_videoBODY: ${{ secrets.QCZJ_videoBODY }} 
          QCZJ_WelfarevideoBODY: ${{ secrets.QCZJ_WelfarevideoBODY }} 
          QCZJ_WelfareBODY: ${{ secrets.QCZJ_WelfareBODY }} 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
